eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-application.herokuapp.com/eureka/
  instance:
    hostname: cloud-gateway-application.herokuapp.com
    homePageUrl: http://${eureka.instance.hostname}/
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443
    
